# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 6 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
#  midly-intersting-facts:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: lowlighter/metrics@latest
#        with:
#          filename: metrics.plugin.habits.facts.svg
#          token: ${{ secrets.METRICS_TOKEN }}
#          base: ""
#          plugin_habits: yes
#          plugin_habits_facts: yes
#          plugin_habits_charts: no
#          plugin_habits_from: 200
#          config_timezone: Europe/Paris
  achivement:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Alexdelia
          template: classic
          base: ""
          config_timezone: Europe/Paris
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
  achivement_all:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Alexdelia
          template: classic
          base: ""
          config_timezone: Europe/Paris
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
  lines-changed:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes
